OrdererOrgs:
  - Name: OrdererOrg
    Domain: ordererorg
    Template:
      Count: 1

PeerOrgs:
  - Name: Org1
    Domain: org1
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org3
    Domain: org3
    Template:
      Count: 3
    Users:
      Count: 1